name: Deploy microservice 1

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    env:
      VERSION: ${{ github.sha }}
      CONTAINER_REGISTRY: ${{ secrets.CONTAINER_REGISTRY }}
      REGISTRY_UN: ${{ secrets.REGISTRY_UN }}
      REGISTRY_PW: ${{ secrets.REGISTRY_PW }}

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE.
      - uses: actions/checkout@v3

      # Makes the scripts executable
      - name: Make scripts executable
        run: chmod +x ./scripts/*.sh

      # Log in to container registry
      - name: Log in to container registry
        run: echo ${{ secrets.REGISTRY_PW }} | docker login ${{ secrets.CONTAINER_REGISTRY }} -u ${{ secrets.REGISTRY_UN }} --password-stdin

      # Builds the Docker image
      - name: Build
        run: ./scripts/build-image.sh ${{ github.sha }}

      # Publishes the Docker image to the container registry
      - name: Publish
        run: ./scripts/push-image.sh

      # Installs Kubectl and connects it to the cluster
      - uses: tale/kubectl-action@v1
        with:
          base64-kube-config: ${{ secrets.KUBE_CONFIG }}
          kubectl-version: v1.30.2
